name: MBINCompiler-test-data

on:
  push:
    branches: 'master'

jobs:
  build:
    name: Package files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip the data folder
        run: |
          mkdir dist
          zip dist/data.zip -r data

      - name: Store zip for release
        uses: actions/upload-artifact@v4
        with:
          name: test-data
          include-hidden-files: true
          path: |
            dist/data.zip
            data/.version

  release:
    name: Release MBINCompiler-test-data
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Collect artefacts for release
        uses: actions/download-artifact@v4
        with:
          name: test-data

      - name: Get MBINCompiler-test-data tag version
        run: echo "VERSION=$(cat ./data/.version)" >> $GITHUB_ENV

      - name: Upload resources to release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          files: dist/data.zip
          body: MBINCompiler test data for NMS Steam BuildID ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
